# Generated by Django 4.0.3 on 2022-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jwt_auth', '0001_initial'),
        ('projects', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('join_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_projects', to='projects.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_requests', to='join_requests.request'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
